name: update

on:
  schedule:
    # at AM 6:50 on Saturday, JST
    # - cron: '50 21 * * 5'
    - cron: '50 * * * *'

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run generate
      - run: yarn run build
      - run: |
          if ! git diff --exit-code >/dev/null 2>&1
          then
            git config --global user.email '<>'
            git config --global user.name 'GitHub Actions'
            git checkout -b $BRANCH
            git add --all .
            git commit --message 'update data files'
            git push $REMOTE $BRANCH
          fi
        env:
          REMOTE: https://${{ secrets.REPOSITORY_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          BRANCH: github-actions/update-data
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: github-actions/update-data
          destination_branch: master
          pr_title: update holidays data
          pr_reviewer: sasaplus1
          pr_assignee: sasaplus1
          github_token: ${{ secrets.GITHUB_TOKEN }}
