name: update

on:
  schedule:
    # at AM 7:10 on Wednesday, JST
    # - cron: '10 22 * * 2'
    - cron: '10 * * * *'

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run generate
      - run: yarn run build
      - run: git diff --exit-code
      - uses: peter-evans/create-pull-request@v1.1.1
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PULL_REQUEST_BRANCH: github-actions/update-data
          COMMIT_MESSAGE: update data files
          PULL_REQUEST_TITLE: update holidays data
